const portfolioList = [
	{
		category:'portfolio-filter-app',
		title:'睿畜保APP-启动页面',
		type:'APP界面设计',
		img:'http://pic.yupoo.com/xenia530/ec4d659c/ce27d5fa.jpg'
	},
	{
		category:'portfolio-filter-app',
		title:'睿畜保APP-启动页面',
		type:'APP界面设计',
		img:'http://pic.yupoo.com/xenia530/9eec6f89/e57b510c.jpg'
	},
	{
		category:'portfolio-filter-vi',
		title:'插画',
		type:'VI视觉设计',
		img:'http://pic.yupoo.com/xenia530/d4afdcce/0ae80ec6.jpg'
	},
	{
		category:'portfolio-filter-app',
		title:'查猪价小程序',
		type:'APP界面设计',
		img:'http://pic.yupoo.com/xenia530/73fa9ce2/8f82c88e.jpg'
	},
	{
		category:'portfolio-filter-web',
		title:'睿畜医生WEB界面',
		type:'WEB网页设计',
		img:'http://pic.yupoo.com/xenia530/13b9ffaa/ce274295.jpg'
	},
	{
		category:'portfolio-filter-web',
		title:'登录注册',
		type:'WEB网页设计',
		img:'http://pic.yupoo.com/xenia530/207e8f5a/ae93f0b2.jpg'
	},
	{
		category:'portfolio-filter-web',
		title:'WEB元素',
		type:'WEB网页设计',
		img:'http://pic.yupoo.com/xenia530/8517ef4b/c4057e74.jpg'
	},
	{
		category:'portfolio-filter-vi',
		title:'日历插画',
		type:'VI视觉设计',
		img:'http://pic.yupoo.com/xenia530/3ec5d26a/3ecaddf1.jpg'
	},
	{
		category:'portfolio-filter-vi',
		title:'员工卡',
		type:'VI视觉设计',
		img:'http://pic.yupoo.com/xenia530/affe510e/5d48c2af.jpg'
	},
	{
		category:'portfolio-filter-web',
		title:'睿畜科技可视化展示',
		type:'WEB网页设计',
		img:'http://pic.yupoo.com/xenia530/fd46d86d/0faf9df0.jpg'
	},
	{
		category:'portfolio-filter-app',
		title:'睿畜保APP界面',
		type:'APP界面设计',
		img:'http://pic.yupoo.com/xenia530/1a4fc41c/e71f6932.jpg'
	},
	{
		category:'portfolio-filter-vi',
		title:'插画练习',
		type:'VI视觉设计',
		img:'http://pic.yupoo.com/xenia530/deec6f61/3bcf03a8.jpg'
	}, 
]

